### ISSUE TITLE
Incompatible License of dependencies

### ISSUE THREAD

**Issue by bmack** [TYPO3GmbH/ext-mediamanager#21]
Several dependencies (such as "vaadin/vaadin-split-layout" and "material/mwc-menu") use Apache 2.0 License, which isn't compatible with GPL2 (only GPL3). Incorporating them into Core would make TYPO3 GPL3 (thus, making TYPO3 incompatible with extensions which are GPL2-only, such as EXT:phpmyadmin).

**Comment by tmaroschik** [comment]
Especially for mwc-menu there are no good replacements. In order to get it merged into TYPO3, we propose integrating those components under question by copying the relevant files into the respective media manager components and thus relicensing those under the GPLv2. Sublicensing of Apache 2.0 licensed work is possible when the original copyright is kept. Patents do not apply to both libraries, so this could be the easiest solution. Copyright is sufficiently kept when a NOTICE file is put next to the LICENSE file and the initial authors/sources are mentioned (see here for an example https://infra.apache.org/licensing-howto.html#example-notice)

Should we proceed this way?

**Comment by Lefaux** [comment]
@bmack @benjaminkott @NeoBlack sounds feasible to me.
Please respond within this week so we can move forward here, thanks :)

**Comment by bmack** [comment]
@Lefaux already discussed on thursday via voice that @tmaroschik includes the needed source files with an additional information in the affected files about the License change. I'm no lawyer but sounds feasable to me.

**Comment by tmaroschik** [comment]
Fixed through #41
